### ISSUE TITLE
Link to your script

### ISSUE THREAD

**Issue by Hippyjake** [BobyMCbobs/GiDeviceInfoMenu#1]
I'm putting together argos scripts in a issue on the argos repo. Would you mind if I add a link?
https://github.com/p-e-w/argos/issues/13

**Comment by BobyMCbobs** [comment]
Yeah sure! I'd love people to use my script!

**Comment by Hippyjake** [comment]
Thanks!

**Comment by BobyMCbobs** [comment]
Here's an updated link, it's been renamed

**Comment by Hippyjake** [comment]
Ha your new name got my attention! Updated.
And closed
